### ISSUE TITLE
Example not showing debugging?

### ISSUE THREAD

**Issue by polx** [oasislabs/wasi-runner#12]
It seems to me that the example at https://oasislabs.github.io/wasi-runner/dist/ is produced by this repository. However, while I see the mention of a map file at the end of `rot13.wasm`, I don't see any download of a map in either Chromium or Firefox.

Was I too dumb to omit a detail?
Thanks very much for https://medium.com/oasislabs/webassembly-debugging-bec0aa93f8c6 where explanations are quite good already (but sadly insufficient to get me running).

**Comment by willscott** [comment]
try opening the 'debugger' / developer tools controls in the browser and reloading the page. You're looking for a `rot13.c` source file. It may require a page reload with developer tools open for the map to be noticed and parsed by the browser.

**Comment by polx** [comment]
Ouch... that is interesting and super good news.
Indeed, there appears `rot13.c` if reloading with the debugger on! (the dev-tools alone is not sufficient).

Thanks, clarifying this on the medium article would be helpful!
(e.g. "Here's a demo... Firefox." add sentence: "Note that you may need to reload with the debugger open to let the C code appear.") 

In firefox-dev-ed I could not add a breakpoint, do you know if there's an extra setting?
In iridium 2020-01 (a chromium) I could.

paul

**Comment by willscott** [comment]
I don't think firefox has breakpoint debugging of wasm (or source-mapped wasm) yet

**Comment by polx** [comment]
FYI: it now works the same way in Firefox and in Chromium.

One drawback compared to when I tested this in March is that each C-line takes quite some clicks to get to the next... I suppose that the "skip" only skips a Wasm-line and this can take tens for a C-line.
I've been preparing a webpack plugin to package C and C++ codebases and your demo showed me how to get that one to work in debug mode too. 

Thanks!
